### ISSUE TITLE
Storyboarding for "building monster" + charging part of charge2

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#48]
Planning out the formation of the monster.

**Comment by minifigmaster125** [comment]
Changed title to reflect the assignment a little, better. As I understand it, Sara is still tweaking the boards. They are up in week 9 of the drive for anyone to look at and comment on. Will probably close soon.

**Comment by public-float-artMajor** [comment]
I looked at the boards and am wondering about this one:

![01](https://cloud.githubusercontent.com/assets/4197056/6888279/c6445e20-d62d-11e4-93ea-2c0cdaac3033.png)

How formed are the mini blobs at the bottom (since they look like they have eyes)? Just wondering incase the look of them here isn't absolute.
Will they be like mini versions of the rigged nightmare and are just engulfed with smoke before rising into the big monster? Or are they more like the rounded blobs here (i.e. some animated emitter with a pair of glowing eyes parented to it)?
